# Our build command includes "bundle" to make support Asciidoc format, making sure Asciidoctor gets installed:
[build]
  publish = "public"
  command = "bundle && hugo"

# The Production Context applies to the branch you have configured as main branch to deploy:
[context.production.environment]
  HUGO_VERSION = "0.31"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# The Deploy Preview Context applies to every Deploy Preview you create: 
[context.deploy-preview.environment]
  HUGO_VERSION = "0.31"

# The Branch Deploy Context applies to all non-master branches deployed, whether they are in a Deploy Preview or not:
[context.branch-deploy.environment]
  HUGO_VERSION = "0.31"

# Besides these three predefined contexts, you can also use branch names as context names:
[context.preview.environment]
  HUGO_BASEURL = "https://preview--suitedocs.netlify.com/"
  HUGO_ENABLEGITINFO = "true"
